services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./app:/usr/local/src/app
      # - ./scripts:/usr/local/src/scripts
      - node_modules:/usr/local/src/app/node_modules

volumes:
  node_modules:
