services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    tty: true
    volumes:
      - ./app:/usr/local/src/app
      - node_modules:/usr/local/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      # CHANGE THE DEFAULT EMAIL AND PASSWORD
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '3002:80'
    depends_on:
      - db

volumes:
  node_modules:
  pgdata:
